"""
Artifact Store - Storage component for Agent Runner artifacts.

This module provides storage, retrieval, and management of artifacts
(diffs, logs, test results) generated by Agent Runners.
"""

from necrocode.artifact_store.models import (
    ArtifactMetadata,
    ArtifactType,
)
from necrocode.artifact_store.exceptions import (
    ArtifactStoreError,
    ArtifactNotFoundError,
    StorageError,
    StorageFullError,
    IntegrityError,
    LockTimeoutError,
)
from necrocode.artifact_store.config import ArtifactStoreConfig
from necrocode.artifact_store.storage_backend import (
    StorageBackend,
    FilesystemBackend,
    S3Backend,
    GCSBackend,
)
from necrocode.artifact_store.compression_engine import (
    CompressionEngine,
    CompressionResult,
    DecompressionResult,
)
from necrocode.artifact_store.metadata_manager import MetadataManager
from necrocode.artifact_store.lock_manager import ArtifactLockManager
from necrocode.artifact_store.artifact_store import ArtifactStore

__all__ = [
    "ArtifactMetadata",
    "ArtifactType",
    "ArtifactStoreError",
    "ArtifactNotFoundError",
    "StorageError",
    "StorageFullError",
    "IntegrityError",
    "LockTimeoutError",
    "ArtifactStoreConfig",
    "StorageBackend",
    "FilesystemBackend",
    "S3Backend",
    "GCSBackend",
    "CompressionEngine",
    "CompressionResult",
    "DecompressionResult",
    "MetadataManager",
    "ArtifactLockManager",
    "ArtifactStore",
]
