"""
Example: Review Comment Posting

This example demonstrates how to use the Review & PR Service to post
automatic comments on pull requests, including test failure notifications.

Requirements: 6.1, 6.2, 6.3, 6.4, 6.5
"""

import logging
from pathlib import Path

from necrocode.review_pr_service.pr_service import PRService
from necrocode.review_pr_service.config import PRServiceConfig, GitHostType
from necrocode.review_pr_service.models import PullRequest, PRState, CIStatus
from necrocode.task_registry.models import Task

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

logger = logging.getLogger(__name__)


def example_basic_comment():
    """Example: Post a basic comment to a PR."""
    logger.info("=== Example: Basic Comment Posting ===")
    
    # Create configuration
    config = PRServiceConfig(
        git_host_type=GitHostType.GITHUB,
        repository="owner/repo",
        api_token="your-github-token",
    )
    
    # Initialize PR Service
    pr_service = PRService(config)
    
    # Post a simple comment
    pr_service.post_comment(
        pr_id="123",
        message="This is a test comment from NecroCode!",
        details={
            "Status": "In Review",
            "Priority": "High",
            "Assigned To": "developer@example.com"
        }
    )
    
    logger.info("Basic comment posted successfully")


def example_test_failure_comment():
    """Example: Post a test failure comment with details."""
    logger.info("=== Example: Test Failure Comment ===")
    
    # Create configuration with auto-comment enabled
    config = PRServiceConfig(
        git_host_type=GitHostType.GITHUB,
        repository="owner/repo",
        api_token="your-github-token",
    )
    
    # Ensure auto-comment is enabled
    config.ci.auto_comment_on_failure = True
    
    # Initialize PR Service
    pr_service = PRService(config)
    
    # Simulate test results
    test_results = {
        "total": 50,
        "passed": 45,
        "failed": 5,
        "skipped": 0,
        "duration": 123.45,
        "failed_tests": [
            {
                "name": "test_user_authentication",
                "error": "AssertionError: Expected status code 200, got 401"
            },
            {
                "name": "test_database_connection",
                "error": "ConnectionError: Unable to connect to database"
            },
            {
                "name": "test_api_endpoint",
                "error": "TimeoutError: Request timed out after 30 seconds"
            },
            {
                "name": "test_data_validation",
                "error": "ValueError: Invalid email format"
            },
            {
                "name": "test_permission_check",
                "error": "PermissionError: User lacks required permissions"
            }
        ]
    }
    
    # Post test failure comment
    pr_service.post_test_failure_comment(
        pr_id="123",
        test_results=test_results,
        error_log_url="https://ci.example.com/builds/456/logs",
        artifact_links={
            "Test Report": "https://artifacts.example.com/test-report.html",
            "Coverage Report": "https://artifacts.example.com/coverage.html",
            "Error Screenshots": "https://artifacts.example.com/screenshots.zip"
        }
    )
    
    logger.info("Test failure comment posted successfully")


def example_custom_comment_template():
    """Example: Use custom comment template."""
    logger.info("=== Example: Custom Comment Template ===")
    
    # Create a custom comment template
    custom_template_path = Path("templates/custom-comment.md")
    custom_template_path.parent.mkdir(parents=True, exist_ok=True)
    
    custom_template_content = """
## 🤖 Automated Review Comment

{{message}}

{% if details %}
### 📊 Details
| Key | Value |
|-----|-------|
{% for key, value in details.items() %}
| {{key}} | {{value}} |
{% endfor %}
{% endif %}

### 🔗 Useful Links
- [CI Dashboard](https://ci.example.com)
- [Documentation](https://docs.example.com)
- [Support](https://support.example.com)

---
*This comment was automatically generated by NecroCode Review & PR Service*
*If you have questions, please contact the DevOps team*
"""
    
    with open(custom_template_path, 'w') as f:
        f.write(custom_template_content)
    
    logger.info(f"Created custom template: {custom_template_path}")
    
    # Create configuration with custom template
    config = PRServiceConfig(
        git_host_type=GitHostType.GITHUB,
        repository="owner/repo",
        api_token="your-github-token",
    )
    
    # Set custom template path
    config.template.comment_template_path = str(custom_template_path)
    
    # Initialize PR Service
    pr_service = PRService(config)
    
    # Post comment using custom template
    pr_service.post_comment(
        pr_id="123",
        message="Your pull request has been reviewed and approved!",
        details={
            "Reviewer": "senior-dev@example.com",
            "Review Date": "2024-01-15",
            "Approval Status": "✅ Approved",
            "Comments": "Great work! Code looks clean."
        },
        use_template=True
    )
    
    logger.info("Comment with custom template posted successfully")


def example_disable_auto_comments():
    """Example: Disable automatic comments."""
    logger.info("=== Example: Disable Auto-Comments ===")
    
    # Create configuration with auto-comment disabled
    config = PRServiceConfig(
        git_host_type=GitHostType.GITHUB,
        repository="owner/repo",
        api_token="your-github-token",
    )
    
    # Disable auto-comment on failure
    config.ci.auto_comment_on_failure = False
    
    logger.info(f"Auto-comment on failure: {config.ci.auto_comment_on_failure}")
    
    # Initialize PR Service
    pr_service = PRService(config)
    
    # This will not post a comment because auto-comment is disabled
    test_results = {
        "total": 10,
        "passed": 8,
        "failed": 2,
        "skipped": 0
    }
    
    pr_service.post_test_failure_comment(
        pr_id="123",
        test_results=test_results
    )
    
    logger.info("Auto-comment was skipped (disabled in config)")


def example_comment_without_template():
    """Example: Post comment without using template."""
    logger.info("=== Example: Comment Without Template ===")
    
    # Create configuration
    config = PRServiceConfig(
        git_host_type=GitHostType.GITHUB,
        repository="owner/repo",
        api_token="your-github-token",
    )
    
    # Initialize PR Service
    pr_service = PRService(config)
    
    # Post comment without template (plain text)
    pr_service.post_comment(
        pr_id="123",
        message="## Manual Review Required\n\nThis PR requires manual review due to security changes.",
        details={
            "Security Impact": "High",
            "Requires Approval From": "Security Team",
            "Estimated Review Time": "2-3 days"
        },
        use_template=False  # Don't use template
    )
    
    logger.info("Plain text comment posted successfully")


def example_integration_with_ci_monitoring():
    """Example: Integration with CI status monitoring."""
    logger.info("=== Example: CI Integration ===")
    
    # Create configuration
    config = PRServiceConfig(
        git_host_type=GitHostType.GITHUB,
        repository="owner/repo",
        api_token="your-github-token",
    )
    
    # Enable CI monitoring and auto-comments
    config.ci.enabled = True
    config.ci.auto_comment_on_failure = True
    config.ci.update_pr_on_status_change = True
    
    # Initialize PR Service
    pr_service = PRService(config)
    
    # Simulate CI failure detection
    pr_id = "123"
    ci_status = CIStatus.FAILURE
    
    logger.info(f"CI status changed to: {ci_status.value}")
    
    # Update labels based on CI status
    pr_service.update_labels_for_ci_status(pr_id, ci_status)
    
    # Post failure comment
    test_results = {
        "total": 100,
        "passed": 95,
        "failed": 5,
        "skipped": 0,
        "duration": 456.78,
        "failed_tests": [
            {"name": "test_critical_feature", "error": "Feature broken"}
        ]
    }
    
    pr_service.post_test_failure_comment(
        pr_id=pr_id,
        test_results=test_results,
        error_log_url="https://ci.example.com/logs/789"
    )
    
    logger.info("CI failure handled with comment and label update")


def main():
    """Run all examples."""
    print("Review Comment Examples")
    print("=" * 60)
    
    try:
        # Note: These examples require valid API tokens and PR IDs
        # Uncomment the examples you want to run
        
        # example_basic_comment()
        # example_test_failure_comment()
        # example_custom_comment_template()
        # example_disable_auto_comments()
        # example_comment_without_template()
        # example_integration_with_ci_monitoring()
        
        logger.info("All examples completed successfully!")
        
    except Exception as e:
        logger.error(f"Example failed: {e}", exc_info=True)


if __name__ == "__main__":
    main()
